### ISSUE TITLE
Executable products in repository

### ISSUE THREAD

**Issue by chrissexton** [IUS-CS/project-grenade-developers#34]
The build artifacts should really not be here. Anything that can be built from source and changes every time you build it should be added to your `/.gitignore` file. I do not know exactly which files are going to get regenerated, but at least `Hungry Dungeon Prototype.exe` reads like a file that is the output of your build process and should be ignored. You will also have to remove them from the repository (with `git rm`)

If you don't do this, then every time somebody builds, it will potentially be part of a commit. If two people build the same binary, you will have a conflict in a nasty way. Keeping build binaries (including any dlls that build too) out of the repository fixes that problem.

**Comment by IAMNameless9t9** [comment]
./gitignore file has been fixed.
